export enum shopTypeID {
    GENERAL_STORE_SHOP_TYPE = 1,
    MEDICAL_STORE_SHOP_TYPE = 2,
    CLOTHS_SHOP_TYPE = 3,
    FOOTWARE_SHOP_TYPE = 4,
    HARDWARE_SHOP_TYPE = 5,
}

export enum shopTypeName {
    GENERAL_STORE_SHOP_TYPE = 'GENERAL STORE',
    MEDICAL_STORE_SHOP_TYPE = 'MEDICAL STORE',
    CLOTHS_SHOP_TYPE = 'CLOTHS STORE',
    FOOTWARE_SHOP_TYPE = 'FOOTWARE STORE',
    HARDWARE_SHOP_TYPE = 'HARDWARE STORE',
}
